> ### **Assignment 2 - Numpy Array Operations** 
>


Write a short introduction about Numpy and list the chosen functions. 

function1 = np.append 

function2 = np.average

function3 = np.arange

function4 = np.squeeze

function5 = np.vstack




In [5]:
import numpy as np

## Function 1 - np.append
np.append function add elements to the end of an array provided that the dimensions of the elements should be same.

In [6]:
# Example 1 - working (change this)
arr1 = [1, 2, 1, 25, 26]
np.append(arr1, [24, 23, 15])


array([ 1,  2,  1, 25, 26, 24, 23, 15])

We can put lists as an element inside the array, then append it with the expected lists or any element regardless of their size.



In [7]:
# Example 2 - working
arr2 = [[2, 4, 5], [6, 7, 8]]
np.append(arr2, [10, 12])
np.append(arr2, [10, 12, 13, 14])

array([ 2,  4,  5,  6,  7,  8, 10, 12, 13, 14])

When axis is specified, arrays must have the same shape.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [14, 15, 16], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Some closing comments about when to use this function.

In [9]:
# Fix
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [[14, 15, 16], [12, 15, 16]], axis = 0)

array([[ 2,  4,  5],
       [ 6,  7,  8],
       [14, 15, 16],
       [12, 15, 16]])

In arr3, index 0 has 2 dimensions, while the element to be appended has 1 dimension, thus breaks down. To fix this, the element to be appended should have 2 dimensions as well.

## Function 2 - np.average

Add some explanations

In [10]:
# Example 1 - working
arr_avg = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
np.average(arr_avg)

50.0

Explanation about example

In [11]:
#Example 2 -working
arr_avg1 = [21, 22, 23, 25, 29]
np.average(arr_avg1)

24.0

Explanation about example

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
avg = [25, 26, 27, 28]
np.average(avg,[21,22,23,24], axis=0)

TypeError: _average_dispatcher() got multiple values for argument 'axis'

Explanation about example (why it breaks and how to fix it)

In [13]:
avg = [25, 26, 27, 28]
np.average(avg)

26.5

Some closing comments about when to use this function.

## Function 3 - np.arange

Add some explanations

In [14]:
# Example 1 - working
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Explanation about example

In [15]:
# Example 2 - working
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

Explanation about example

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange(1,10,int)

TypeError: unsupported operand type(s) for /: 'int' and 'type'

Explanation about example (why it breaks and how to fix it)

In [17]:
np.arange(1,10,2,int)

array([1, 3, 5, 7, 9])

Some closing comments about when to use this function.

## Function 4 - np.squeeze

Add some explanations

In [18]:
# Example 1 - working
X = np.array([[[29], [30], [31]]])
X.shape


(1, 3, 1)

In [19]:
np.squeeze(X,axis=0).shape

(3, 1)

Explanation about example

In [20]:
# Example 2 - working
X1 = np.array([[[29], [30], [31]]])
X1


array([[[29],
        [30],
        [31]]])

In [21]:
np.squeeze(X1,axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

Explanation about example

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
X2 = np.array([[[29], [30], [31]]])
X2.shape

(1, 3, 1)

In [23]:
np.squeeze(X2,axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 5 - np.vstack

Add some explanations

In [24]:
# Example 1 - working
X = np.array([2, 4, 6])
Y = np.array([8, 10, 12])
np.vstack((X,Y))

array([[ 2,  4,  6],
       [ 8, 10, 12]])

Explanation about example

In [25]:
# Example 2 - working
X = np.array([[2], [4], [6]])
Y = np.array([[8], [10], [12]])
np.vstack((X,Y))

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])


Explanation about example

In [26]:
# Example 3 - breaking (to illustrate when it breaks)
x1 = np.array([[2], [4], [6]])
y1 = np.array([8], [10], [12])
np.vstack((x1,y1))

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

Explanation about example (why it breaks and how to fix it)

In [27]:
X1 = np.array([[2], [4], [6]])
Y1 = np.array([[8], [10], [12]])
np.vstack((X1,Y1))

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])

Some closing comments about when to use this function.